eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes[0]:
        id: account-service
        uri: lb://account-service
        predicates[0]: Path=/api/account/**
      routes[1]:
        id: page-service
        uri: lb://page-service
        predicates[0]: Path=/api/page/**
      routes[2]:
        id: token-service
        uri: lb://token-service
        predicates[0]: Path=/api/token/**
      routes[3]:
        id: discovery-server
        uri: http://localhost:8761
        predicates[0]: Path=/eureka/web
        filters[0]: SetPath=/
      routes[4]:
        id: discovery-server-static
        uri: http://localhost:8761
        predicates[0]: Path=/eureka/**
      routes[5]:
        id: video-service
        uri: lb://video-service
        predicates[0]: Path=/api/video/**
logging:
  level:
    org:
      springframework:
        cloud:
          gateway:
            route:
              RouteDefinitionLocator: INFO
            nodeValue: TRACE
    root: INFO

